name: on-pr-main

on:
  pull_request:
    branches:
      - main

jobs:

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  is-rebased:
    name: Is rebased
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - uses: cyberark/enforce-rebase@v2
        with:
          default-branch: main
