name: test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: stable

      - run: go mod download
      - run: go fmt ./...
      - run: go vet ./...
      - run: go test ./... -coverprofile=c.out
